global:
  scrape_interval: 5s
  evaluation_interval: 5s
  external_labels:
    monitor: 'my-monitor'

rule_files:
  #- 'alert.rules'

alerting:
  alertmanagers:
    - static_configs:
      - targets:
        #- mon_prometheus-alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['mon_prometheus:9090']
  - job_name: 'prometheus-node-exporter'
    static_configs:
      - targets: ['mon_node-exporter:9100']
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['mon_cadvisor:8080']
